#!/bin/bash
# SPDX-License-Identifier: MIT
###############################################################################
# nic5.sh  -  Run the PyPSA-Eur Negawatt optimisation on the NIC5/CECI cluster
#
# Strategy: heavy LP solving runs on NIC5 (hmem node + Gurobi), everything else
# stays local. The (small) un-solved networks are prepared LOCALLY, transferred
# to the cluster, the myopic solve chain runs there, and the solved networks are
# pulled back.
#
# Execution model: Snakemake runs on the NIC5 *login* node and submits each rule
# to Slurm via its built-in slurm executor. This matters because NIC5 compute
# nodes have no internet, while Snakemake must reach the data-retrieval storage
# providers when it builds the DAG -- which it does on the login node. The
# compute nodes then only run the solve script (Gurobi via the token server).
#
#   ./cluster/nic5.sh setup            # one-time: install env on the cluster
#   ./cluster/nic5.sh run ref 1h       # full test: prepare+push+solve+wait+pull
#
# or step by step:
#   ./cluster/nic5.sh prepare 1h       # LOCAL: build un-solved inputs @1h
#   ./cluster/nic5.sh push             # rsync code+inputs to the cluster
#   ./cluster/nic5.sh solve ref 1h     # submit ref solve on Slurm
#   ./cluster/nic5.sh solve suff 1h    # submit suff solve (after ref finishes)
#   ./cluster/nic5.sh status           # squeue + tail logs
#   ./cluster/nic5.sh wait             # block until jobs finish
#   ./cluster/nic5.sh pull             # rsync solved results back
#   ./cluster/nic5.sh postprocess ref 6h  # LOCAL: touch solve outputs, run prepare_results
#
# The time resolution (e.g. 1h, 6h, 24h) is passed as the Snakemake
# `sector_opts` wildcard, so NO config file is edited and local runs are
# unaffected.
###############################################################################
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
# shellcheck source=config.sh
source "$HERE/config.sh"
JOBFILE="$HERE/.last_jobs"
mkdir -p "$HERE/logs"

msg()  { printf '\033[1;34m[nic5]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[nic5] WARNING:\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[nic5] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

POSTPROCESS_CONFIG="$HERE/.postprocess_sector_opts.yaml"

# shellcheck disable=SC2086
rssh() { ssh $SSH_OPTS "$REMOTE" "$@"; }
# shellcheck disable=SC2086
rssync() { rsync -e "ssh $SSH_OPTS" "$@"; }

# Read solving.cpus from cluster/config_cluster.yaml (Slurm cpus-per-task).
cluster_cpus() {
    awk '/^solving:/{s=1} s && /^  cpus:/{print $NF; exit}' "$HERE/config_cluster.yaml"
}

# Validate scenario argument for solve/run. "all" is reserved but not supported yet.
resolve_scenario() {
    case "${1:-}" in
        ref|suff) echo "$1" ;;
        all)
            die "solve all is not supported yet: ref and suff share the same cluster checkout and .snakemake/ state, so launching both orchestrators at once can interfere with each other and with Slurm job tracking. Run them separately:
  $0 solve ref <res>
  $0 solve suff <res>"
            ;;
        *)
            die "unknown scenario '$1' (expected ref, suff, or all)"
            ;;
    esac
}

# Build the list of solved-network targets for one scenario / resolution.
solved_targets() {
    local sc=$1 res=$2 y
    for y in $HORIZONS; do
        echo "results/${sc}/networks/base_s_${CLUSTERS}_${OPTS}_${res}_${y}.nc"
    done
}

# Brownfield inputs for the myopic solve chain (used when touching the DAG).
brownfield_targets() {
    local sc=$1 res=$2 y
    for y in $HORIZONS; do
        echo "resources/${sc}/networks/base_s_${CLUSTERS}_${OPTS}_${res}_${y}_brownfield.nc"
    done
}

# Ephemeral Snakemake config overlay: set sector_opts wildcard to the cluster resolution.
write_postprocess_config() {
    local res=$1
    cat > "$POSTPROCESS_CONFIG" <<EOF
# Generated by nic5.sh postprocess — sector_opts must match the cluster solve resolution.
scenario:
  sector_opts:
  - "${res}"
EOF
}

# Align brownfield mtimes with pulled solves so add_brownfield / solve are not re-triggered.
sync_brownfield_mtimestamps() {
    local sc=$1 res=$2 y bf sol
    for y in $HORIZONS; do
        bf="resources/${sc}/networks/base_s_${CLUSTERS}_${OPTS}_${res}_${y}_brownfield.nc"
        sol="results/${sc}/networks/base_s_${CLUSTERS}_${OPTS}_${res}_${y}.nc"
        if [ -f "$REPO/$bf" ] && [ -f "$REPO/$sol" ]; then
            touch -r "$REPO/$sol" "$REPO/$bf"
        fi
    done
}

# Build the list of LOCAL prepare targets (un-solved solve inputs) for a scenario.
prepare_targets() {
    local sc=$1 res=$2 y first
    first=$(echo "$HORIZONS" | awk '{print $1}')
    # first horizon: brownfield from add_existing_baseyear (needs no solve)
    echo "resources/${sc}/networks/base_s_${CLUSTERS}_${OPTS}_${res}_${first}_brownfield.nc"
    # later horizons: prepared (un-solved) base networks
    for y in $HORIZONS; do
        [ "$y" = "$first" ] && continue
        echo "resources/${sc}/networks/base_s_${CLUSTERS}_${OPTS}_${res}_${y}.nc"
    done
    # co2 totals (resolution independent, but make sure they exist)
    for y in $HORIZONS; do
        echo "resources/${sc}/co2_totals_s_${CLUSTERS}_${y}.csv"
    done
}

cmd_prepare() {
    local res=${1:?usage: prepare <resolution e.g. 1h>}
    for sc in $SCENARIOS; do
        msg "Preparing un-solved inputs for '$sc' @ $res (local)"
        # shellcheck disable=SC2046
        ( cd "$REPO" && $LOCAL_RUN snakemake \
            --snakefile "Snakefile_${sc}" \
            --cores "$LOCAL_CORES" \
            --rerun-triggers mtime \
            -- $(prepare_targets "$sc" "$res") )
    done
    msg "Local preparation complete."
}

cmd_push() {
    msg "Syncing repo + inputs to ${REMOTE}:${REMOTE_DIR}"
    rssh "mkdir -p '$REMOTE_DIR'"
    # Everything except the build-only Atlite cutout (several GB, never read by
    # the solve chain) is transferred. Keeping the rest of data/ avoids missing
    # intermediate inputs that would otherwise make Snakemake try to rebuild
    # (and download) upstream rules on the compute node, which has no internet.
    # rsync preserves mtimes, so the pre-built prepared networks stay "current"
    # and only the solve chain runs. The first push is slow (~4 GB over the
    # VPN); subsequent pushes are incremental and fast.
    rssync -arh --no-g \
        --exclude '.git' --exclude '.snakemake' --exclude '.pixi' \
        --exclude 'results' --exclude '__pycache__' --exclude '*.pyc' \
        --exclude 'cluster/logs' --exclude 'cutouts' --exclude 'data/cutout' \
        "$REPO/" "${REMOTE}:${REMOTE_DIR}/"
    # Ship Snakemake's provenance metadata too: without it the compute node
    # falls back to raw filesystem mtimes and would consider locally-built
    # resources stale (triggering rebuilds/downloads). With it, only the solve
    # chain runs.
    if [ -d "$REPO/.snakemake/metadata" ]; then
        rssh "mkdir -p '$REMOTE_DIR/.snakemake'"
        rssync -arh --no-g "$REPO/.snakemake/metadata" "${REMOTE}:${REMOTE_DIR}/.snakemake/"
    fi
    msg "Push complete."
}

# Remote shell prologue: activate the conda env and wire up the Gurobi licence.
REMOTE_ENV='source $HOME/miniforge3/etc/profile.d/conda.sh && conda activate '"$ENV_NAME"' && unset PYTHONPATH && export GRB_LICENSE_FILE=$HOME/gurobi.lic'

cmd_solve() {
    local sc res solve_cpus
    sc=$(resolve_scenario "${1:?usage: solve <scenario> <resolution>  e.g. solve ref 1h}")
    res=${2:?usage: solve <scenario> <resolution>  e.g. solve ref 1h}
    solve_cpus=$(cluster_cpus)
    [ -n "$solve_cpus" ] || die "solving.cpus not set in cluster/config_cluster.yaml"
    : > "$JOBFILE"
    msg "Launching Slurm orchestrator on the login node: scenario=$sc resolution=$res cpus=$solve_cpus"
    local targets log pidf pid
    targets=$(solved_targets "$sc" "$res" | tr '\n' ' ')
    log="cluster/logs/orchestrate_${sc}_${res}.log"
    pidf="cluster/logs/orchestrate_${sc}_${res}.pid"
    # Resource notes (CECI job efficiency):
    # - Do NOT put cpus_per_task in --default-resources: it overrides Gurobi
    #   threads for solve jobs. Set solve cpus via --set-resources instead.
    # - Memory and Gurobi threads come from cluster/config_cluster.yaml.
    # - Partition/runtime come from --default-resources (hmem for all rules).
    rssh "cd '$REMOTE_DIR' && $REMOTE_ENV && \
        setsid bash -c 'snakemake --snakefile Snakefile_${sc} \
            --executor slurm --jobs $MAX_SLURM_JOBS \
            --configfile cluster/config_cluster.yaml \
            --rerun-triggers mtime --keep-going --printshellcmds \
            --default-resources slurm_partition=$SOLVE_PARTITION runtime=$SOLVE_RUNTIME mem_mb=$DEFAULT_MEM_MB \
            --set-resources solve_sector_network_myopic:cpus_per_task=$solve_cpus \
            --set-resources add_brownfield:cpus_per_task=1 \
            -- $targets </dev/null >\"$log\" 2>&1 & echo \$! >\"$pidf\"' </dev/null >/dev/null 2>&1"
    sleep 2
    pid=$(rssh "cat '$REMOTE_DIR/$pidf' 2>/dev/null" | tr -d '[:space:]')
    echo "$sc $res ${pid:-unknown}" >> "$JOBFILE"
    msg "  orchestrator pid ${pid:-unknown} for $sc (log: $log)"
    msg "Track with: $0 status"
}

cmd_stop() {
    msg "Cancelling Slurm jobs and orchestrators on $REMOTE"
    rssh "scancel -u \$(whoami) 2>/dev/null; pkill -f 'bin/snakemake --snakefile' 2>/dev/null || true"
    msg "Stop signalled."
}

# Query live CPU/RSS per thread on compute nodes (same idea as
#   ssh <node> "top -b -n 1 -u \$USER -H"
# but scoped to each Slurm job via its cgroup).
status_job_usage() {
    rssh 'bash -s' <<'REMOTE'
set -uo pipefail
running=$(squeue --me -h -t RUNNING -o "%i|%N|%j|%C|%m" 2>/dev/null || true)
if [ -z "$running" ]; then
    echo "(no running Slurm jobs)"
    exit 0
fi
while IFS='|' read -r jobid node name alloc_cpus alloc_mem; do
    [ -n "$jobid" ] || continue
    echo "--- job $jobid on $node (alloc: ${alloc_cpus} CPUs, ${alloc_mem}) ---"
    short=${name:0:40}
    [ "$short" != "$name" ] && short="${short}..."
    echo "    name: $short"
    if ssh -o ConnectTimeout=5 -o BatchMode=yes -o ForwardX11=no "$node" bash -s "$jobid" <<'NODE'
jobid=$1
mapfile -t job_pids < <(
    find /sys/fs/cgroup/memory/slurm -path "*job_${jobid}*" -name cgroup.procs \
        -exec cat {} \; 2>/dev/null | sort -nu
)
main_pid="" max_rss=0 main_comm=""
for pid in "${job_pids[@]}"; do
    [ -r "/proc/$pid/status" ] || continue
    rss=$(awk '/^VmRSS:/ {print $2}' "/proc/$pid/status" 2>/dev/null)
    comm=$(awk '/^Name:/ {print $2}' "/proc/$pid/status" 2>/dev/null)
    if [ "${rss:-0}" -gt "$max_rss" ]; then
        max_rss=$rss
        main_pid=$pid
        main_comm=$comm
    fi
done
if [ -z "$main_pid" ]; then
    echo "    (no processes in cgroup yet)"
    exit 0
fi
echo "    process: pid=$main_pid ($main_comm), VmRSS=$((max_rss / 1024)) MiB"
echo "    busiest threads (top -b -n 1 -H -p $main_pid, >=1% CPU, max 20):"
printf "    %-10s %6s %6s %10s %5s %s\n" "TID" "%CPU" "%MEM" "RSS" "S" "COMMAND"
top -b -n 1 -H -p "$main_pid" 2>/dev/null | awk '
    NR > 7 && $1 ~ /^[0-9]+$/ {
        tid[n] = $1
        cpupct[n] = $9 + 0
        mempct[n] = $10
        rss[n] = $6
        st[n] = $8
        cmd[n] = $12
        cpu += cpupct[n]
        if ($8 == "R") r++
        n++
    }
    END {
        if (n == 0) exit
        for (i = 0; i < n; i++) order[i] = i
        for (i = 0; i < n - 1; i++) {
            for (j = i + 1; j < n; j++) {
                if (cpupct[order[j]] > cpupct[order[i]]) {
                    t = order[i]; order[i] = order[j]; order[j] = t
                }
            }
        }
        shown = 0
        for (i = 0; i < n; i++) {
            k = order[i]
            if (cpupct[k] < 1.0) break
            if (shown >= 20) break
            printf "    %-10s %6s %6s %10s %5s %s\n", tid[k], cpupct[k], mempct[k], rss[k], st[k], cmd[k]
            shown++
        }
        if (shown == 0) {
            limit = (n < 20 ? n : 20)
            for (i = 0; i < limit; i++) {
                k = order[i]
                printf "    %-10s %6s %6s %10s %5s %s\n", tid[k], cpupct[k], mempct[k], rss[k], st[k], cmd[k]
            }
            shown = limit
        }
        cores = cpu / 100
        printf "    summary: %d thread(s) total (%d running), showing %d busiest, sum %%CPU=%.1f (~%.1f cores)\n", n, r + 0, shown, cpu, cores
    }'
NODE
    then
        :
    else
        echo "    (could not reach $node)"
    fi
done <<< "$running"
REMOTE
}

cmd_status() {
    msg "Slurm queue on $REMOTE (squeue --me):"
    rssh "squeue --me --format='%.18i %.10P %.26j %.8T %.10M %R'" 2>/dev/null
    echo
    msg "Live CPU / memory per thread (top -H on compute nodes):"
    status_job_usage
    [ -f "$JOBFILE" ] || return 0
    while read -r sc res pid; do
        echo
        if rssh "kill -0 $pid" 2>/dev/null; then
            msg "--- orchestrator $sc (pid $pid: RUNNING) ---"
        else
            msg "--- orchestrator $sc (pid $pid: finished) ---"
        fi
        rssh "grep -vE 'Lmod|Try: |module\(s\)|Python/3.7.4' '$REMOTE_DIR/cluster/logs/orchestrate_${sc}_${res}.log' 2>/dev/null | tail -n 12 || echo '(no log yet)'"
        slurm_log=$(rssh "grep -oE 'log: [^)]+' '$REMOTE_DIR/cluster/logs/orchestrate_${sc}_${res}.log' 2>/dev/null | tail -1 | sed 's/^log: //'" | tr -d '\r')
        if [ -n "$slurm_log" ]; then
            echo
            msg "--- Slurm job log (last 20 lines): $slurm_log ---"
            rssh "tail -n 20 '$slurm_log' 2>/dev/null || echo '(log not found)'"
        fi
    done < "$JOBFILE"
}

cmd_wait() {
    [ -f "$JOBFILE" ] || die "no orchestrators recorded ($JOBFILE missing)"
    msg "Waiting for orchestrators to finish..."
    while true; do
        local alive=0
        while read -r sc res pid; do
            rssh "kill -0 $pid" 2>/dev/null && alive=$((alive+1))
        done < "$JOBFILE"
        [ "$alive" -eq 0 ] && break
        printf '\r[nic5] %s orchestrator(s) still running... %s' "$alive" "$(date +%H:%M:%S)"
        sleep 60
    done
    printf '\n'
    msg "All orchestrators finished. Per-scenario outcome:"
    while read -r sc res pid; do
        if rssh "grep -qE 'Nothing to be done|steps \(100%\) done|Complete log' '$REMOTE_DIR/cluster/logs/orchestrate_${sc}_${res}.log'" 2>/dev/null; then
            msg "  $sc: OK"
        else
            msg "  $sc: CHECK LOG (cluster/logs/orchestrate_${sc}_${res}.log) -- may have errors"
        fi
    done < "$JOBFILE"
}

cmd_pull() {
    msg "Pulling results + logs from cluster"
    mkdir -p "$REPO/results" "$HERE/logs"
    rssync -arh --no-g --info=progress2 \
        "${REMOTE}:${REMOTE_DIR}/results/" "$REPO/results/" \
        || msg "(no results dir yet)"
    rssync -arh --no-g \
        "${REMOTE}:${REMOTE_DIR}/cluster/logs/" "$HERE/logs/" || true
    msg "Pull complete. Solved networks are in results/<scenario>/networks/."
}

cmd_postprocess() {
    local sc res touch_targets log
    sc=$(resolve_scenario "${1:?usage: postprocess <scenario> <resolution>  e.g. postprocess ref 6h}")
    res=${2:?usage: postprocess <scenario> <resolution>  e.g. postprocess ref 6h}

    warn "postprocess runs LOCALLY after pull. Scenario=$sc resolution=$res must match the cluster solve."
    warn "Step 1 uses Snakemake --touch: output files are marked up to date WITHOUT running their commands."
    warn "  --touch updates modification times and records that the solve chain is complete; it does NOT re-run Gurobi."
    warn "  --touch does NOT check file contents — only run this after a successful cluster solve and pull."
    warn "  Do not add --forcerun to the touch step; that would execute solve/add_brownfield and overwrite pulled .nc files."

    local t
    for t in $(solved_targets "$sc" "$res"); do
        [ -f "$REPO/$t" ] || die "missing $t — run './cluster/nic5.sh pull' (and solve) first"
    done

    sync_brownfield_mtimestamps "$sc" "$res"
    write_postprocess_config "$res"
    touch_targets=$(printf '%s\n' $(solved_targets "$sc" "$res") $(brownfield_targets "$sc" "$res") | tr '\n' ' ')
    log="$HERE/logs/postprocess_${sc}_${res}.log"

    msg "Touching solve-chain outputs (Snakemake --touch) for $sc @ $res"
    # shellcheck disable=SC2086
    ( cd "$REPO" && $LOCAL_RUN snakemake \
        --snakefile "Snakefile_${sc}" \
        --cores 1 \
        --rerun-triggers mtime \
        --configfile "$POSTPROCESS_CONFIG" \
        --touch \
        -- $touch_targets ) 2>&1 | tee "$log"

    msg "Running prepare_results and its post-processing dependencies for $sc @ $res"
    ( cd "$REPO" && $LOCAL_RUN snakemake \
        --snakefile "Snakefile_${sc}" \
        --cores "$LOCAL_CORES" \
        --rerun-triggers mtime \
        --configfile "$POSTPROCESS_CONFIG" \
        -R prepare_results ) 2>&1 | tee -a "$log"

    msg "Post-processing complete (log: $log)."
}

cmd_setup() {
    msg "One-time cluster setup on $REMOTE"
    rssh "mkdir -p '$REMOTE_DIR'"
    rssync -arh --no-g "$HERE/cluster_setup.sh" "${REMOTE}:${REMOTE_DIR}/cluster/cluster_setup.sh"
    rssync -arh --no-g "$REPO/envs/environment.yaml" "${REMOTE}:${REMOTE_DIR}/envs/environment.yaml"
    rssh "bash '$REMOTE_DIR/cluster/cluster_setup.sh'"
    msg "Setup finished."
}

cmd_run() {
    local sc res
    sc=$(resolve_scenario "${1:?usage: run <scenario> <resolution>  e.g. run ref 1h}")
    res=${2:?usage: run <scenario> <resolution>  e.g. run ref 1h}
    cmd_prepare "$res"
    cmd_push
    cmd_solve "$sc" "$res"
    cmd_wait
    cmd_pull
    cmd_postprocess "$sc" "$res"
}

cmd_shell() { ssh $SSH_OPTS -t "$REMOTE" "cd '$REMOTE_DIR'; exec bash -l"; }

case "${1:-}" in
    setup)   shift; cmd_setup "$@";;
    prepare) shift; cmd_prepare "$@";;
    push)    shift; cmd_push "$@";;
    solve)   shift; cmd_solve "$@";;
    stop)    shift; cmd_stop "$@";;
    status)  shift; cmd_status "$@";;
    wait)    shift; cmd_wait "$@";;
    pull)        shift; cmd_pull "$@";;
    postprocess) shift; cmd_postprocess "$@";;
    run)         shift; cmd_run "$@";;
    shell)   shift; cmd_shell "$@";;
    *) cat <<EOF
Usage: $0 <command> [args...]
  setup                      one-time: install conda env + Gurobi licence on the cluster
  prepare <res>              LOCAL: build un-solved solve inputs at <res> (e.g. 1h)
  push                       rsync code + inputs to the cluster (scratch)
  solve <scenario> <res>     submit one scenario on hmem (ref or suff; see "all" below)
  stop                       cancel Slurm jobs and orchestrators on the cluster
  status                     show queue, per-job thread CPU/RSS, orchestrator logs
  wait                       block until all submitted jobs finish
  pull                       rsync solved results back into ./results
  postprocess <scenario> <res>
                             LOCAL (after pull): --touch solve outputs, then prepare_results
  run <scenario> <res>       prepare + push + solve + wait + pull + postprocess
  shell                      open an interactive shell in the cluster repo

  Examples:
    $0 solve ref 1h
    $0 solve suff 1h
    $0 solve all 1h          (not supported yet — runs ref then suff separately instead)
EOF
       exit 1;;
esac
